# Generated by Django 5.1.1 on 2024-09-25 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_date_alter_product_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_item_purchased',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 9, 34, 45, 994697)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 9, 34, 45, 994287)),
        ),
    ]
