# Generated by Django 5.1.1 on 2024-09-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image_alter_order_date_and_more'),
        ('store', '0007_product_daily_restock_quantity_alter_order_date_and_more'),
    ]

    operations = [
    ]
