# Generated by Django 5.1.1 on 2024-09-26 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20240926_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 17, 50, 37, 115711)),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 17, 50, 37, 103665)),
        ),
    ]
