# Generated by Django 5.1.1 on 2024-10-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_order_date_alter_order_status_and_more'),
        ('store', '0020_remove_customer_phone_number_alter_order_date_and_more'),
    ]

    operations = [
    ]
