# Generated by Django 5.1.1 on 2024-10-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_date_alter_order_status_and_more'),
        ('store', '0022_remove_product_image_product_image_url_and_more'),
    ]

    operations = [
    ]
