# Generated by Django 5.0.6 on 2024-10-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_customer_user_alter_order_date_and_more'),
        ('store', '0025_alter_order_date_alter_order_status_and_more'),
    ]

    operations = [
    ]
